apiVersion: backstage.io/v1beta1
kind: API
metadata:
  name: todo
  description: Simple Go API
  links:
    - url: https://github.com/benbooth493/hello-world
      title: Simple Go API Github
      icon: code
spec:
  type: openapi
  lifecycle: experimental
  owner: ben
  definition:
    $text: https://github.com/benbooth493/hello-world/blob/main/docs/swagger.json
