apiVersion: backstage.io/v1beta1
kind: Component
metadata:
  name: todo-service
  description: Simple Go service
  labels:
    system: web-apps
  annotations:
    backstage.io/kubernetes-id: todo
    github.com/project-slug: benbooth493/projects/1
  tags:
    - go
  links:
    - url: https://github.com/benbooth493/hello-world
      title: Simple Go Service Github
      icon: code
spec:
  type: service
  lifecycle: experimental
  owner: ben
  providesApis:
    - todo-api
