apiVersion: backstage.io/v1beta1
kind: Component
metadata:
  name: hello-world
  description: Simple Go API
  labels:
    system: web-apps
  tags:
    - go
    - api
  links:
    - url: https://github.com/benbooth493/hello-world
      title: Simple Go API Github
      icon: code
spec:
  type: service
  lifecycle: experimental
  owner: ben
