apiVersion: backstage.io/v1beta1
kind: Component
metadata:
  name: todo-service
  description: Simple Go service
  labels:
    system: web-apps
  tags:
    - go
  links:
    - url: https://github.com/benbooth493/hello-world
      title: Simple Go Service Github
      icon: code
spec:
  type: service
  lifecycle: experimental
  owner: ben
  providesApi:
    - todo-api
