apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo
  labels:
    app: todo
    env: experimental
    backstage.io/kubernetes-id: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
        env: experimental
        backstage.io/kubernetes-id: todo
    spec:
      containers:
        - name: todo
          image: benbooth493/todo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: todo
  labels:
    env: experimental
    backstage.io/kubernetes-id: todo
spec:
  selector:
    app: todo
  ports:
    - port: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo
  labels:
    env: experimental
    backstage.io/kubernetes-id: todo
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: "/todo"
            backend:
              service:
                name: todo
                port:
                  number: 8080
